name: ${PROJECT_NAME:-ft_transcendence}

services:
  # Core application services
  ms-frontend:
    container_name: frontend
    build:
      context: ./packages/ms-frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "${FRONTEND_PORT:-3010}:3010"
    networks:
      - ${NETWORK_NAME:-ft-net}
    depends_on:
      - logstash

  ms-auth:
    container_name: authentication
    build:
      context: ./packages/ms-auth
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-here}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-http://localhost:3010/auth/google/callback}
      - WEBAUTHN_RP_ID=${WEBAUTHN_RP_ID:-localhost}
      - WEBAUTHN_RP_NAME=${WEBAUTHN_RP_NAME:-ft_transcendence}
      - WEBAUTHN_ORIGIN=${WEBAUTHN_ORIGIN:-http://localhost:3010}
    volumes:
      - ./packages/ms-auth/prisma/auth.db:/app/prisma/auth.db
      - ./packages/ms-auth/src:/app/src
    networks:
      - ${NETWORK_NAME:-ft-net}
    depends_on:
      - logstash

  ms-game:
    container_name: game
    build:
      context: .
      dockerfile: ./packages/ms-game/Dockerfile
    env_file: ./packages/ms-game/.env
    ports:
      - "${GAME_PORT:-3003}:3003"
    networks:
      - ${NETWORK_NAME:-ft-net}
    depends_on:
      - logstash

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-9.0.2}
    environment:
      - discovery.type=${ELASTICSEARCH_DISCOVERY_TYPE:-single-node}
      - ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS:--Xms512m -Xmx512m}
      - xpack.security.enabled=${ELASTICSEARCH_SECURITY_ENABLED:-false}
      - "_JAVA_OPTIONS=${ELASTICSEARCH_JAVA_OPTIONS:--XX:UseSVE=0}"
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
    networks:
      - ${NETWORK_NAME:-ft-net}
    volumes:
      - ${ELASTICSEARCH_DATA_VOLUME:-esdata}:/usr/share/elasticsearch/data
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: ${ELASTICSEARCH_HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${ELASTICSEARCH_HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${ELASTICSEARCH_HEALTH_CHECK_RETRIES:-5}

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION:-9.0.2}
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=${KIBANA_ELASTICSEARCH_HOSTS:-http://elasticsearch:9200}
      - xpack.security.enabled=${KIBANA_SECURITY_ENABLED:-false}
      - "_JAVA_OPTIONS=${KIBANA_JAVA_OPTIONS:--XX:UseSVE=0}"
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    networks:
      - ${NETWORK_NAME:-ft-net}

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:${LOGSTASH_VERSION:-9.0.2}
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "${LOGSTASH_TCP_PORT:-5001}:5001"
      - "${LOGSTASH_HTTP_PORT:-9600}:9600"
    environment:
      - LS_JAVA_OPTS=${LOGSTASH_JAVA_OPTS:--Xmx256m -Xms256m}
    networks:
      - ${NETWORK_NAME:-ft-net}
    volumes:
      - ./devops/logstash/pipeline:/usr/share/logstash/pipeline

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ${PROMETHEUS_CONFIG_PATH:-./devops/prometheus/prometheus.yml}:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_ALERTS_PATH:-./devops/prometheus/alerts.yml}:/etc/prometheus/alerts.yml
    networks:
      - ${NETWORK_NAME:-ft-net}

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT:-3002}:3002"
    volumes:
      - ${GRAFANA_PROVISIONING_PATH:-./devops/grafana/provisioning}:/etc/grafana/provisioning
      - ${GRAFANA_DATA_VOLUME:-grafana-data}:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=${GRAFANA_ALLOW_SIGN_UP:-false}
    depends_on:
      - prometheus
      - elasticsearch
    networks:
      - ${NETWORK_NAME:-ft-net}

volumes:
  esdata:
  grafana-data:

networks:
  ft-net:
    driver: bridge
