global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ms-game"
    static_configs:
      - targets: ["game:3002"]
    metrics_path: "/metrics"
  - job_name: "ms-auth"
    static_configs:
      - targets: ["authentication:3001"]
    metrics_path: "/metrics"
  - job_name: "ms-blockchain"
    static_configs:
      - targets: ["blockchain:3004"]
    metrics_path: "/metrics"
  - job_name: "ms-tournament"
    static_configs:
      - targets: ["tournament:3003"]
    metrics_path: "/metrics"

