global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: prometheus
      password: changeme
    static_configs:
      - targets: ["localhost:9090"]

  # Microservices (HTTPS)
  - job_name: "ms-game"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["game:3002"]
    metrics_path: "/metrics"
    
  - job_name: "ms-auth"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["authentication:3001"]
    metrics_path: "/metrics"
    
  - job_name: "ms-blockchain"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["blockchain:3004"]
    metrics_path: "/metrics"
    
  - job_name: "ms-tournament"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["tournament:3003"]
    metrics_path: "/metrics"