global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "frontend:3000"
    static_configs:
      - targets: ["frontend:3000"]
    metrics_path: "/metrics"
  - job_name: "game-service"
    static_configs:
      - targets: ["game:3006"]
    metrics_path: "/metrics"
  - job_name: "ms-auth"
    static_configs:
      - targets: ["authentication:3001"]
    metrics_path: "/metrics"
  - job_name: "blockchain"
    static_configs:
      - targets: ["blockchain:3004"]
    metrics_path: "/metrics"
  - job_name: "tournament-service"
    static_configs:
      - targets: ["tournament:3003"]
    metrics_path: "/metrics"
