tls_server_config:
  cert_file: /etc/prometheus/certs/prometheus.crt
  key_file: /etc/prometheus/certs/prometheus.key

basic_auth_users:
  prometheus: $2y$10$FdLhSBNjesamL1nUA3xdW.s/6AY7JGZtZ8lngQXGrN9eC33TksY4m
