tls_server_config:
  cert_file: /etc/prometheus/certs/prometheus.crt
  key_file: /etc/prometheus/certs/prometheus.key

basic_auth_users:
  prometheus: $2y$10$mMgLMoCrQoFmezrycd6B/um6ym.Vh1DsWfJGlow1N1uV1yCbYSDmy
