tls_server_config:
  cert_file: /etc/prometheus/certs/prometheus.crt
  key_file: /etc/prometheus/certs/prometheus.key

basic_auth_users:
  prometheus: $2y$10$2pnC3iifaJZax05CYX0qx.KqEqdNZZxlxFO97IK.B689yYOCm9sta
