tls_server_config:
  cert_file: /etc/prometheus/certs/prometheus.crt
  key_file: /etc/prometheus/certs/prometheus.key

basic_auth_users:
  prometheus: $2y$10$DPe.0HW5wqj.IxZhl1e.COMo.VsFvjMvhjM1CMq0rv.1NUxwawbXK
